- name: app
  format: $remote_addr - $remote_user [$time_local] "$method $request $protocol" $request_time-$upstream_response_time $status $body_bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for"
  source_files:
    - ./test/nginx.log
  static_config:
    foo: foo
  relabel_config: 
    source_labels: 
      - request
      - method
      - status
    replacement:
      request: 
        trim: "?"
        replace:
          - target: /v1.0/example/\d+
            value: /v1.0/example/:id